import{a as x,S as b,i}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const S=15;async function g(s,r=1){try{return(await x.get("https://pixabay.com/api/",{params:{key:"52810941-a867c2a4f7105994d43c555c3",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:S}})).data}catch(e){return console.log(e),{hits:[],totalHits:0}}}document.querySelector(".form");const m=document.querySelector(".loader"),y=document.querySelector(".gallery"),l=document.querySelector(".load-more"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const r=s.map(e=>`
        <li class="gallery-item">
            <div>
                <a class="gallery-link" href="${e.largeImageURL}">
                <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" width=450 height=300 />
                <div class="gallery-info">
                    <p class="gallery-text"> <span class ="span-text">Likes</span> ${e.likes}</p>
                    <p class="gallery-text"> <span class ="span-text">Views</span> ${e.views}</p>
                    <p class="gallery-text"> <span class ="span-text">Comments</span> ${e.comments}</p>
                    <p class="gallery-text"> <span class ="span-text">Downloads</span> ${e.downloads}</p>
                </div>
            </div>
        </li>
    `).join("");y.insertAdjacentHTML("beforeend",r),q.refresh()}function P(){y.innerHTML=""}function v(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}function $(){l.classList.remove("hidden")}function p(){l.classList.add("hidden")}const f=document.querySelector(".form"),c=f.elements["search-text"],E=c.placeholder;f.addEventListener("submit",M);l.addEventListener("click",O);let n=1,w="";const R=15;let h=0;function M(s){s.preventDefault(),v();const r=f.elements["search-text"].value.trim();if(P(),!r){i.error({title:"Error",message:"Please enter a search query."}),u();return}w=r,n=1,c.placeholder="",g(r,n).then(e=>{const a=e.hits;if(h=Math.ceil(e.totalHits/R),!a||a.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(a),n<h?$():p()}).catch(e=>{i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p()}).finally(()=>{u(),c.value="",c.placeholder=E})}async function O(){n++,l.disabled=!0,v();try{const r=(await g(w,n)).hits;L(r),n>=h&&(p(),i.info({message:"You've reached the end of search results.",position:"topRight"}));const e=document.querySelector(".gallery-item");if(e){const{height:a}=e.getBoundingClientRect();window.scrollBy({left:0,top:a*2,behavior:"smooth"})}}catch(s){i.error({title:"Error",message:s.message||"Something went wrong",position:"topRight"})}finally{u(),l.disabled=!1}}
//# sourceMappingURL=index.js.map
