import{a as b,S as x,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const S=15;async function g(s,r=1){try{return(await b.get("https://pixabay.com/api/",{params:{key:"52810941-a867c2a4f7105994d43c555c3",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:S}})).data}catch(e){return console.log(e),{hits:[],totalHits:0}}}document.querySelector(".form");const y=document.querySelector(".loader"),m=document.querySelector(".gallery"),c=document.querySelector(".load-more"),q=new x(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const r=s.map(e=>`
        <li class="gallery-item">
            <div>
                <a class="gallery-link" href="${e.largeImageURL}">
                <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" width=350 height=250 />
                <div class="gallery-info">
                    <p class="gallery-text"> <span class ="span-text">Likes</span> ${e.likes}</p>
                    <p class="gallery-text"> <span class ="span-text">Views</span> ${e.views}</p>
                    <p class="gallery-text"> <span class ="span-text">Comments</span> ${e.comments}</p>
                    <p class="gallery-text"> <span class ="span-text">Downloads</span> ${e.downloads}</p>
                </div>
            </div>
        </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),q.refresh()}function P(){m.innerHTML=""}function w(){y.classList.remove("hidden")}function u(){y.classList.add("hidden")}function R(){c.classList.remove("hidden")}function l(){c.classList.add("hidden")}const f=document.querySelector(".form"),p=f.elements["search-text"],$=p.placeholder;f.addEventListener("submit",M);c.addEventListener("click",O);let i=1,v="";const E=15;let h=0;async function M(s){s.preventDefault(),P(),l(),w();const r=f.elements["search-text"].value.trim();if(!r){n.error({title:"Error",message:"Please enter a search query.",position:"topRight"}),u();return}v=r,i=1,p.placeholder="";try{const e=await g(r,i),a=e.hits;if(h=Math.ceil(e.totalHits/E),!a||a.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l();return}L(a),i<h?R():(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l()}finally{u(),p.placeholder=$}}async function O(){i++,c.disabled=!0,w();try{const r=(await g(v,i)).hits;L(r),i>=h&&(l(),n.info({message:"You've reached the end of search results.",position:"topRight"}));const e=document.querySelector(".gallery-item");if(e){const{height:a}=e.getBoundingClientRect();window.scrollBy({left:0,top:a*2,behavior:"smooth"})}}catch(s){n.error({title:"Error",message:s.message||"Something went wrong",position:"topRight"})}finally{u(),c.disabled=!1}}
//# sourceMappingURL=index.js.map
